@startuml

App *-- OrionBot
OrionBot o--> Command
Command <|-- Ping

class App{
--
+ void main(String[] args)
}

class OrionBot {
    - Map<String, Command> commands
    - String discordToken
--
    + void listen()
    + String getCommand(MessageCreateEvent event)
    + Command selectCommand(String name)
    - void loadCommands()
}

abstract Command {
    + {abstract} void executeCommand(MessageCreateEvent event);
    + {abstract} String getHelp()
}

Class Ping{

}
@enduml