@startuml
title Command Execution

actor user as user
participant OrionBot as bot
participant Command as command

user-->bot: MessageCreateEvent event
bot->bot: String getCommand(MessageCreateEvent event)
bot->bot: Command selectCommand(String name)
bot->command: void executeCommand(MessageCreateEvent event)
command-->>user: String messsage
@enduml