@startuml

actor user as user
participant OrionBot as bot
participant Command as command

user-->bot: MessageCreateEvent
bot->bot: selectCommand(String name)
bot->bot: execCommand(Command command)
bot->command: void execute()
command-->>user: String

@enduml